image: postgres:11.5

Build:
     stage: build
     tags:
       - dev
     script:
       - echo Starting postgres
       - /usr/local/bin/docker-entrypoint.sh postgres &
       - sleep 10
       - echo Starting pipeline build
       - cd /builds/cheshire-datasystems/dba-team/pg-mv-fast-refresh-githubrunner
       - cp .pipeline_module_set_variables.sh module_set_variables.sh 
       - /builds/cheshire-datasystems/dba-team/pg-mv-fast-refresh-githubrunner/run_pipeline_checks.sh build
       
MV-Refresh:
     stage: test
     tags:
       - dev
     script:
       - echo Starting postgres
       - /usr/local/bin/docker-entrypoint.sh postgres &
       - sleep 10
       - echo Starting pipeline build
       - cd /builds/cheshire-datasystems/dba-team/pg-mv-fast-refresh-githubrunner
       - cp .pipeline_module_set_variables.sh module_set_variables.sh 
       - /builds/cheshire-datasystems/dba-team/pg-mv-fast-refresh-githubrunner/run_pipeline_checks.sh build
       - echo Starting pipeline MV refresh
       - cd /builds/cheshire-datasystems/dba-team/pg-mv-fast-refresh-githubrunner
       - /builds/cheshire-datasystems/dba-team/pg-mv-fast-refresh-githubrunner/run_pipeline_checks.sh test

Module-Destroy:
     stage: test
     tags:
       - dev
     script:
       - echo Starting postgres
       - /usr/local/bin/docker-entrypoint.sh postgres &
       - sleep 10
       - echo Starting pipeline build
       - cd /builds/cheshire-datasystems/dba-team/pg-mv-fast-refresh-githubrunner
       - cp .pipeline_module_set_variables.sh module_set_variables.sh 
       - /builds/cheshire-datasystems/dba-team/pg-mv-fast-refresh-githubrunner/run_pipeline_checks.sh build
       - echo Starting destroy of module
       - cd /builds/cheshire-datasystems/dba-team/pg-mv-fast-refresh-githubrunner
       - /builds/cheshire-datasystems/dba-team/pg-mv-fast-refresh-githubrunner/run_pipeline_checks.sh destroy     



