REVOKE USAGE ON SCHEMA cron FROM :MODULEOWNER;
REVOKE ALL ON SCHEMA cron FROM :MODULEOWNER;
REVOKE ALL PRIVILEGES ON SCHEMA cron FROM :MODULEOWNER;
REVOKE ALL ON ALL TABLES in schema cron FROM :MODULEOWNER;
REVOKE ALL ON ALL sequences in schema cron FROM :MODULEOWNER;